# 公共配置
mybatis-plus:
  typeAliasesPackage: com.baomidou.springboot.entity

  ### 全局策略配置
  global-config:
    db-config:
      id-type: input
      field-strategy: not-empty
      db-type: mysql
      table-underline: false
      #逻辑删除配置
      sql-injector : com.baomidou.mybatisplus.mapper.LogicSqlInjector
      logic-delete-value : 0
      #配置逻辑删除字段为0是删除
      logic-not-delete-value : 1
      #配置逻辑删除字段为1是未删除

  configuration:
    #true为开启驼峰功能
    map-underscore-to-camel-case: false
    #mybatis二级缓存
    cache-enabled: false
    #忽略空值时的jdbcType
    jdbc-type-for-null: null

        
# dev:开发环境 prod:正式环境
spring.profiles.active: dev
spring:
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 50MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 100MB